// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJPI1zh3qAxMWTIcm2rMAAdVkA69rr9JE',
    appId: '1:729954962607:web:543b082358aa5a469f185a',
    messagingSenderId: '729954962607',
    projectId: 'video-gen-app-16b41',
    authDomain: 'video-gen-app-16b41.firebaseapp.com',
    storageBucket: 'video-gen-app-16b41.firebasestorage.app',
    measurementId: 'G-D16SJSJ2YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZHEJEgvQQkP2XEdX7SP3eXR7J8KoP_I',
    appId: '1:729954962607:android:915735a37e738a409f185a',
    messagingSenderId: '729954962607',
    projectId: 'video-gen-app-16b41',
    storageBucket: 'video-gen-app-16b41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbkg_2wN0ku0DgXO91fv4-Nb3meX9Wuns',
    appId: '1:729954962607:ios:e4245128e3ed33999f185a',
    messagingSenderId: '729954962607',
    projectId: 'video-gen-app-16b41',
    storageBucket: 'video-gen-app-16b41.firebasestorage.app',
    iosClientId:
        '729954962607-gn0dggmm785hcb2eq181l9ju9grn792n.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbkg_2wN0ku0DgXO91fv4-Nb3meX9Wuns',
    appId: '1:729954962607:ios:e4245128e3ed33999f185a',
    messagingSenderId: '729954962607',
    projectId: 'video-gen-app-16b41',
    storageBucket: 'video-gen-app-16b41.firebasestorage.app',
    iosClientId:
        '729954962607-gn0dggmm785hcb2eq181l9ju9grn792n.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJPI1zh3qAxMWTIcm2rMAAdVkA69rr9JE',
    appId: '1:729954962607:web:1e9cb835bac7c3589f185a',
    messagingSenderId: '729954962607',
    projectId: 'video-gen-app-16b41',
    authDomain: 'video-gen-app-16b41.firebaseapp.com',
    storageBucket: 'video-gen-app-16b41.firebasestorage.app',
    measurementId: 'G-MH4KYTL8BH',
  );
}
