import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers";
import type { Env } from "../env.js";
import { EXPORT_CHUNK_LIMIT, EXPORT_MANIFEST_BYTE_LIMIT, streamDeleteIsAlreadyGone } from "./account-lifecycle-policy.js";

type ExportParams={requestId:string;userId:string};
type DeletionParams={requestId:string;userId:string;scheduledFor:number};
type ExportTable={name:string;sql:string};
const PAGE_SIZE=25;
const MAX_EXPORT_CHUNKS=EXPORT_CHUNK_LIMIT;
const MAX_MANIFEST_BYTES=EXPORT_MANIFEST_BYTE_LIMIT;
const EXPORT_TABLES:ExportTable[]=[
	{name:"projects",sql:"SELECT rowid AS _cursor,* FROM projects WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"brands",sql:"SELECT rowid AS _cursor,* FROM brands WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"brand_versions",sql:"SELECT rowid AS _cursor,* FROM brand_versions WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"brand_mutations",sql:"SELECT rowid AS _cursor,* FROM brand_mutations WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"token_transactions",sql:"SELECT rowid AS _cursor,* FROM token_transactions WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"notifications",sql:"SELECT rowid AS _cursor,* FROM notifications WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"render_jobs",sql:"SELECT rowid AS _cursor,* FROM render_jobs WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"user_characters",sql:"SELECT rowid AS _cursor,* FROM user_characters WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"user_character_versions",sql:"SELECT ucv.rowid AS _cursor,ucv.* FROM user_character_versions ucv JOIN user_characters uc ON uc.id=ucv.character_id WHERE uc.user_id=? AND ucv.rowid>? ORDER BY ucv.rowid LIMIT ?"},
	{name:"generation_jobs",sql:"SELECT rowid AS _cursor,* FROM generation_jobs WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"generation_attempts",sql:"SELECT ga.rowid AS _cursor,ga.* FROM generation_attempts ga JOIN generation_jobs gj ON gj.id=ga.job_id WHERE gj.user_id=? AND ga.rowid>? ORDER BY ga.rowid LIMIT ?"},
	{name:"generation_events",sql:"SELECT ge.rowid AS _cursor,ge.* FROM generation_job_events ge JOIN generation_jobs gj ON gj.id=ge.job_id WHERE gj.user_id=? AND ge.rowid>? ORDER BY ge.rowid LIMIT ?"},
	{name:"generation_assets",sql:"SELECT ga.rowid AS _cursor,ga.* FROM generation_assets ga JOIN generation_jobs gj ON gj.id=ga.job_id WHERE gj.user_id=? AND ga.rowid>? ORDER BY ga.rowid LIMIT ?"},
	{name:"credit_reservations",sql:"SELECT rowid AS _cursor,* FROM credit_reservations WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"voice_favorites",sql:"SELECT rowid AS _cursor,* FROM voice_favorites WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"play_purchases",sql:"SELECT rowid AS _cursor,id,user_id,product_id,order_id,token_amount,created_at FROM play_purchases WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
	{name:"notification_preferences",sql:"SELECT rowid AS _cursor,* FROM notification_preferences WHERE user_id=? AND rowid>? ORDER BY rowid LIMIT ?"},
];

async function maybeEmail(env:Env,userId:string,subject:string,text:string,html:string):Promise<boolean>{const r=await env.DB.prepare("SELECT u.email,p.email_enabled FROM user u LEFT JOIN notification_preferences p ON p.user_id=u.id WHERE u.id=?").bind(userId).first<{email:string;email_enabled:number|null}>();if(!r?.email||r.email_enabled!==1)return false;try{await env.EMAIL.send({to:r.email,from:{email:env.EMAIL_FROM_ADDRESS,name:env.EMAIL_FROM_NAME},subject,text,html});return true;}catch(error){console.error(JSON.stringify({event:"transactional_email_failed",userId,subject,error:error instanceof Error?error.message:String(error)}));return false;}}
async function hmac(secret:string,value:string):Promise<string>{const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const bytes=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("");}
const streamMissing=streamDeleteIsAlreadyGone;
async function deletePrefix(env:Env,bucket:R2Bucket,prefix:string,step:WorkflowStep,label:string):Promise<number>{let page=0,total=0;for(;;){const result=await step.do(`delete-prefix-${label}-${page}`,async()=>{const listed=await bucket.list({prefix,limit:1000});if(listed.objects.length)await bucket.delete(listed.objects.map(object=>object.key));return{count:listed.objects.length};});total+=result.count;if(result.count===0)break;page++;}return total;}

export class DataExportWorkflow extends WorkflowEntrypoint<Env,ExportParams>{
	async run(event:WorkflowEvent<ExportParams>,step:WorkflowStep):Promise<void>{const {requestId,userId}=event.payload;
		const accepted=await step.do("claim-export",async()=>{const r=await this.env.DB.prepare("UPDATE data_export_requests SET status='processing',error_code=NULL WHERE id=? AND user_id=? AND workflow_instance_id=? AND status='queued'").bind(requestId,userId,event.instanceId).run();return(r.meta.changes??0)===1;});if(!accepted)return;
		const prefix=`users/${userId}/exports/${requestId}`;const chunks:Array<{table:string;key:string;count:number}>=[];
		const profileKey=`${prefix}/chunks/profile.json`;const profile=await step.do("export-profile",{sensitive:"output"},async()=>{const r=await this.env.DB.prepare("SELECT id,name,email,email_verified,image,phone,tokens,created_at,updated_at FROM user WHERE id=?").bind(userId).first();await this.env.EXPORTS_BUCKET.put(profileKey,JSON.stringify(r??null),{httpMetadata:{contentType:"application/json"}});return{key:profileKey,count:r?1:0};});chunks.push({table:"profile",...profile});
		let tooLarge=false;exportTables:for(const table of EXPORT_TABLES){let cursor=0,page=0;for(;;){if(chunks.length>=MAX_EXPORT_CHUNKS){tooLarge=true;break exportTables;}const key=`${prefix}/chunks/${table.name}-${String(page).padStart(6,"0")}.json`;const result=await step.do(`export-${table.name}-${page}`,{sensitive:"output"},async()=>{const pageResult=await this.env.DB.prepare(table.sql).bind(userId,cursor,PAGE_SIZE).all<Record<string,unknown>>();const values=pageResult.results,nextCursor=Number(values.at(-1)?._cursor??cursor);for(const value of values)delete value._cursor;if(values.length)await this.env.EXPORTS_BUCKET.put(key,JSON.stringify(values),{httpMetadata:{contentType:"application/json"}});return{cursor:nextCursor,count:values.length,key};});if(result.count===0)break;cursor=result.cursor;chunks.push({table:table.name,key:result.key,count:result.count});page++;if(result.count<PAGE_SIZE)break;}}
		const completedAt=Date.now(),expiresAt=completedAt+7*24*60*60_000,manifestKey=`${prefix}/manifest.json`;const manifest=JSON.stringify({exportVersion:1,generatedAt:new Date(completedAt).toISOString(),userId,chunks});
		if(tooLarge||new TextEncoder().encode(manifest).byteLength>MAX_MANIFEST_BYTES){await deletePrefix(this.env,this.env.EXPORTS_BUCKET,`${prefix}/`,step,"oversized-export");await step.do("fail-oversized-export",async()=>{await this.env.DB.prepare("UPDATE data_export_requests SET status='failed',error_code='export_too_large' WHERE id=? AND user_id=? AND workflow_instance_id=? AND status='processing'").bind(requestId,userId,event.instanceId).run();});return;}
		await step.do("store-manifest",()=>this.env.EXPORTS_BUCKET.put(manifestKey,manifest,{httpMetadata:{contentType:"application/json",cacheControl:"private, no-store"},customMetadata:{userId,requestId,expiresAt:String(expiresAt)}}));
		await step.do("mark-export-ready",async()=>{await this.env.DB.batch([this.env.DB.prepare("UPDATE data_export_requests SET status='ready',completed_at=?,expires_at=?,object_key=?,error_code=NULL WHERE id=? AND user_id=? AND workflow_instance_id=? AND status='processing'").bind(completedAt,expiresAt,manifestKey,requestId,userId,event.instanceId),this.env.DB.prepare("INSERT OR IGNORE INTO notifications (id,user_id,type,title,message,is_read,push_sent,email_sent,deep_link,dedupe_key,metadata,created_at) VALUES (?,?, 'data_export_ready','Your data export is ready','Download it from Account settings before it expires',0,0,0,'/settings',?,?,?)").bind(crypto.randomUUID(),userId,`data-export:${requestId}`,JSON.stringify({requestId,expiresAt}),completedAt)]);});
		await step.do("notify-export-ready",async()=>{const sent=await maybeEmail(this.env,userId,"Your Zellyo data export is ready","Your requested export is ready in Account settings and expires in 7 days.","<p>Your requested Zellyo export is ready in Account settings and expires in 7 days.</p>");if(sent)await this.env.DB.prepare("UPDATE notifications SET email_sent=1 WHERE user_id=? AND dedupe_key=?").bind(userId,`data-export:${requestId}`).run();});
	}
}

export class AccountDeletionWorkflow extends WorkflowEntrypoint<Env,DeletionParams>{
	async run(event:WorkflowEvent<DeletionParams>,step:WorkflowStep):Promise<void>{const {requestId,userId,scheduledFor}=event.payload;
		await step.do("notify-cooling-off",async()=>{await maybeEmail(this.env,userId,"Zellyo account deletion scheduled",`Your account deletion is scheduled for ${new Date(scheduledFor).toISOString()}. You can cancel it in Account settings before then.`,`<p>Your account deletion is scheduled for ${new Date(scheduledFor).toISOString()}. You can cancel it in Account settings before then.</p>`);});
		await step.sleepUntil("cooling-off-period",new Date(scheduledFor));
		const claimed=await step.do("claim-deletion",async()=>{if(await this.env.DB.prepare("SELECT request_id FROM account_deletion_tombstones WHERE request_id=?").bind(requestId).first())return false;const r=await this.env.DB.prepare("UPDATE account_deletion_requests SET status='deleting' WHERE id=? AND user_id=? AND status='scheduled' AND workflow_instance_id=? AND scheduled_for<=?").bind(requestId,userId,event.instanceId,Date.now()).run();return(r.meta.changes??0)===1;});if(!claimed)return;
		let cursor="",page=0,streamCount=0;for(;;){const json=await step.do(`stream-assets-${page}`,{sensitive:"output"},async()=>JSON.stringify((await this.env.DB.prepare("SELECT ga.id,ga.object_key FROM generation_assets ga JOIN generation_jobs gj ON gj.id=ga.job_id WHERE gj.user_id=? AND ga.storage='stream' AND ga.id>? ORDER BY ga.id LIMIT ?").bind(userId,cursor,PAGE_SIZE).all<{id:string;object_key:string}>()).results));const values=JSON.parse(json) as Array<{id:string;object_key:string}>;if(!values.length)break;await step.do(`delete-stream-assets-${page}`,{retries:{limit:5,delay:"30 seconds",backoff:"exponential"}},async()=>{for(const item of values){try{await this.env.STREAM.video(item.object_key).delete();}catch(error){if(!streamMissing(error))throw error;}}});streamCount+=values.length;cursor=values.at(-1)!.id;page++;if(values.length<PAGE_SIZE)break;}
		const counts={stream:streamCount,assets:await deletePrefix(this.env,this.env.ASSETS_BUCKET,`users/${userId}/`,step,"assets"),renders:await deletePrefix(this.env,this.env.RENDERS_BUCKET,`${userId}/renders/`,step,"renders"),uploads:await deletePrefix(this.env,this.env.UPLOADS_BUCKET,`user-uploads/${userId}/`,step,"uploads"),exports:await deletePrefix(this.env,this.env.EXPORTS_BUCKET,`users/${userId}/exports/`,step,"exports")};
		await step.do("delete-d1-tenant-and-audit",async()=>{const now=Date.now(),pseudonym=await hmac(this.env.DELETION_TOMBSTONE_SECRET,userId);await this.env.DB.batch([this.env.DB.prepare("INSERT OR IGNORE INTO account_deletion_tombstones (request_id,pseudonymous_user_hash,workflow_instance_id,asset_counts,deleted_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM account_deletion_requests WHERE id=? AND user_id=? AND status='deleting' AND workflow_instance_id=?)").bind(requestId,pseudonym,event.instanceId,JSON.stringify(counts),now,requestId,userId,event.instanceId),this.env.DB.prepare("DELETE FROM user WHERE id=? AND EXISTS (SELECT 1 FROM account_deletion_requests WHERE id=? AND user_id=? AND status='deleting' AND workflow_instance_id=?)").bind(userId,requestId,userId,event.instanceId)]);if(await this.env.DB.prepare("SELECT id FROM user WHERE id=?").bind(userId).first())throw new Error("tenant_d1_delete_not_committed");});
	}
}
